---
- name: Switch Nginx configuration based on deployment color
  hosts: localhost
  become: true  # Use sudo
  tasks:
    - name: Backup existing Nginx configuration
      command: cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
      ignore_errors: true  # Ignore if the backup fails (if it doesn't exist)

    - name: Update Nginx configuration for the current color
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              server_name localhost;

              location / {
                  proxy_pass http://localhost:8081;  # Default port for blue
                  {% if color == 'green' %}
                  proxy_pass http://localhost:8082;  # Use port for green if color is green
                  {% endif %}
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
              }

              location ~ /\.ht {
                  deny all;
              }
          }

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
