- name: Switch NGINX Configuration for 3.110.134.164
  hosts: localhost
  become: yes
  vars:
    current_color: "{{ deployment_color }}"  # Passed from Jenkins (either 'blue' or 'green')

  tasks:
    - name: Set NGINX configuration for blue-green deployment
      copy:
        content: |
          # NGINX configuration for 13.126.122.36
          # This configuration dynamically routes traffic to the active deployment (blue or green).
          upstream backend {
              {% if current_color == 'green' %}
              server localhost:8082;  # Green environment
              {% else %}
              server localhost:8081;  # Blue environment
              {% endif %}
              # Use IP Hash for session persistence
              ip_hash;
          }

          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              root /var/www/html;
              server_name 3.110.130.211;

              # Dynamically route to the active deployment container
              location / {
                  proxy_pass http://backend;  # Proxy to the correct backend (blue or green)
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
                  proxy_cache_bypass $http_upgrade;
                  proxy_read_timeout 90;  # Increased timeout for long-running requests
                  proxy_connect_timeout 30;  # Avoid 502 errors during connection switching
              }

              # Security: Block access to hidden files
              location ~ /\.(ht|HT) {
                  deny all;
              }
              
              # Expose NGINX status for Prometheus metrics
              location /nginx_status {
                  stub_status on;
                  access_log off;
                  allow 3.110.130.211;  # Allow Prometheus to access NGINX status on EC2 IP
                  deny all;  # Deny external access
            }
          }
        dest: /etc/nginx/sites-available/default
      notify:
        - reload nginx

    - name: Test NGINX configuration
      command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0

  handlers:
    - name: reload nginx
      command: nginx -s reload
